#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --time=4:00:00
#SBATCH --job-name=Co-hcp
#SBATCH --output=log
#SBATCH --error=err

module load mpi/impi-5.0.3 intel/mkl-11.2.3 vasp/vasp-5.4.4

mpirun vasp_std
